### ISSUE TITLE
compilation error events.d.ts

### ISSUE THREAD

**Issue by mochoamat** [thisissoon/angular-infinite-scroll#9] opened 2018-03-07 19:26 UTC
Running in development launches the error message, but can run.

Running the build --prod fails and breaks.

node_modules\@thisissoon\angular-infinite-scroll\src\app\infinite-scroll\shared\events.d.ts:2:34
Initializers are not allowed in ambient contexts.

change the line:
export declare const eventScroll = "scroll";

with line: 
export declare const eventScroll: string;

to fixup the issue.

I run the build with success

**Comment by edoparearyee** [comment] 2018-04-09 15:04
@mochoamat I'm unable to reproduce your issue using the latest version of the angular cli and angular. Please include steps to reproduce the issue as well as build tools and the environment you are using.

I'm going to close this issue but feel free to reopen if can reproduce the issue.

**Closed as completed by edoparearyee** 2018-04-09 15:04 UTC
